MAT_SCRIPT := zero_fill_interp.m
GIR_DIR := /v/raid5/usr/jhulet/gir

link: remove
	ln -s ${PWD}/${MAT_SCRIPT} ${GIR_DIR}/matlab_scripts/${MAT_SCRIPT}

remove:
	rm -f ${GIR_DIR}/matlab_scripts/${MAT_SCRIPT}
